development:
  adapter: postgresql
  host: localhost
  username: tealtan
  database: birmingham
  pool: 5
  timeout: 5000

test:
  adapter: postgres
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: ENV['DB_HOST']
  username: ENV['DB_USER']
  password: ENV['DB_PASSWORD']
  database: ENV['DB_NAME']